robot_hw_node:
  ros__parameters:
    StandHumanoidController:
      stand_pos:
      # leg
        - -0.15
        - -0.00
        - -0.05
        - 0.30
        - -0.16
        - 0.00

        - -0.15
        - 0.00
        - 0.05
        - 0.30
        - -0.16
        - 0.00

      # waist
        - 0.0
        - 0.0
        - 0.0

      # head
        - 0.0
        - 0.0

      # arm
        - 0.1
        - 0.1
        - -0.2
        - -0.2
        - 0.0
        - 0.0
        - 0.0

        - 0.1
        - -0.1
        - 0.2
        - -0.2
        - 0.0
        - 0.0
        - 0.0

      stand_kp:
        - 580.0
        - 500.0
        - 500.0
        - 660.0
        - 400.0
        - 400.0

        - 580.0
        - 500.0
        - 500.0
        - 660.0
        - 400.0
        - 400.0

        - 800.0
        - 800.0
        - 800.0

        - 10.0
        - 10.0

        - 80.0
        - 80.0
        - 80.0
        - 50.0
        - 40.0
        - 20.0
        - 10.0

        - 80.0
        - 80.0
        - 80.0
        - 50.0
        - 40.0
        - 20.0
        - 10.0

      stand_kd:
        - 8.0
        - 6.0
        - 6.0
        - 8.0
        - 2.0
        - 2.0

        - 8.0
        - 6.0
        - 6.0
        - 8.0
        - 2.0
        - 2.0

        - 8.0
        - 8.0
        - 8.0

        - 1.0
        - 1.0
        
        - 3.0
        - 3.0
        - 2.0
        - 3.0
        - 2.0
        - 1.0
        - 1.0

        - 3.0
        - 3.0
        - 2.0
        - 3.0
        - 2.0
        - 1.0
        - 1.0
