robot_hw_node:
  ros__parameters:
    MimicHumanoidController:
      joint_num: 31
      policy_dir: "/policy/default"

      motion_frames: 764
      control:
        # PD Drive parameters: (useless here)
        action_scale:
          - 0.25
          - 0.25
          - 0.5
          - 0.25
          - 0.5
          - 0.5

          - 0.25
          - 0.25
          - 0.5
          - 0.25
          - 0.5
          - 0.5
          
          - 0.5
          - 0.5
          - 0.5
          
          - 0.1
          - 0.1
          
          - 0.1
          - 0.1
          - 0.1
          - 0.1
          - 0.1
          - 0.1
          - 0.1

          - 0.1
          - 0.1
          - 0.1
          - 0.1
          - 0.1
          - 0.1
          - 0.1

        decimation: 10
        user_torque_limit:
          [
            160.0,
            120.0,
            120.0,
            160.0,
            80.0,
            80.0,

            160.0,
            120.0,
            120.0,
            160.0,
            80.0,
            80.0,
            
            120.0,
            120.0,
            120.0,

            3.0,
            3.0,

            80.0,
            80.0,
            80.0,
            80.0,
            10.0,
            10.0,
            10.0,
            
            80.0,
            80.0,
            80.0,
            80.0,
            10.0,
            10.0,
            10.0,
          ]
        kp:
          - 280.
          - 280.
          - 100.
          - 280.
          - 20.
          - 20.

          - 280.
          - 280.
          - 100.
          - 280.
          - 20.
          - 20.

          - 80.
          - 80.
          - 80.

          - 5.
          - 5.

          - 80.
          - 80.
          - 80.
          - 80.
          - 40.
          - 40.
          - 40.

          - 80.
          - 80.
          - 80.
          - 80.
          - 40.
          - 40.
          - 40.
        kd:
          - 5.0
          - 5.0
          - 5.0
          - 4.0
          - 2.0
          - 2.0

          - 5.0
          - 5.0
          - 5.0
          - 4.0
          - 2.0
          - 2.0

          - 3.0
          - 3.0
          - 3.0

          - 0.5
          - 0.5

          - 4.0
          - 4.0
          - 4.0
          - 4.0
          - 3.0
          - 3.0
          - 3.0

          - 4.0
          - 4.0
          - 4.0
          - 4.0
          - 3.0
          - 3.0
          - 3.0

      normalization:
        clip_scales:
          clip_observations: 100.
          clip_actions: 100.
        obs_scales:
          lin_vel: 1.0
          ang_vel: 0.25
          dof_pos: 1.0
          dof_vel: 0.05
          height_measurements: 5.0

      size:
        motion_ref_size: 39
        actions_size: 31
        observations_size: 100 # 6+31+31+31+63(1+31+7)
        obs_history_length: 10
        encoder_output_size:
          - 3.
          - 32.