robot_hw_node:
  ros__parameters:
    robot_controllers:
      - robot_controllers/DampingHumanoidController
      - robot_controllers/StandHumanoidController
      - robot_controllers/MimicHumanoidController
