robot_hw_node:
  ros__parameters:
    DampingHumanoidController:
      joint_num: 31
      damping_kd:
        - 10.0
        - 10.0
        - 10.0
        - 10.0
        - 4.0
        - 4.0

        - 10.0
        - 10.0
        - 10.0
        - 10.0
        - 4.0
        - 4.0

        - 6.0
        - 6.0
        - 6.0

        - 2.0
        - 2.0

        - 10.0
        - 10.0
        - 5.0
        - 5.0
        - 2.0
        - 2.0
        - 2.0

        - 10.0
        - 10.0
        - 5.0
        - 5.0
        - 2.0
        - 2.0
        - 2.0